apiVersion: v1
kind: Service
metadata:
        name: svc1
        labels:
                name: sample-svc
spec:
        ports:
        - port: 80
          targetPort: 80
          protocol: TCP
        selector:
                app: app-v1
        type: LoadBalancer
