apiVersion: v1
kind: Service
metadata:
        name: svc2
        labels:
                name: sample-svc
spec:
        ports:
        - port: 80
          targetPort: 80
          protocol: TCP
        selector:
                app: app-v2
        type: LoadBalancer
